### ISSUE TITLE
improve debugging docs

### ISSUE THREAD

**Issue by gidden** [cyclus/release#59]
I have been trying to debug the test_abi failure for 2-3 days now and have found CI to be very very confusing. This is due to two necessary obfuscations, using polyphemus -- does it simply launch the fast run spec? who knows? -- and conda -- how does it get the right branch to test? grepping shows the branch name only exists is fetch/cyclus.git

```
cyclusci@submit-1:~/cyclus--cyclus--1100 > grep -r 'failtest' .
./fetch/cyclus.git:git_path = cyclus;cd cyclus;git checkout failtest
``` 

I understand there are many layers going on here; however I was one of the people who helped set up the original batlab jobs, and have set up such jobs for other projects, and I have found this terribly difficult. In fact, I have failed, after 2-3 days, to debug this "simple" issue. 

Heck, even using `ssh_nmi` into a test run and running `CYCL/build.sh` fails:
```
slot4@exec-110:/var/lib/condor/execute/slot4/dir_10843/userdir$ ./CYCL/build.sh 
+ set -e
+ ./bin/conda-inst.sh
+ set -e
++ uname
+ UNAME=Linux
+ MINICONDA_VER=3.7.0
++ pwd
+ export PATH=/var/lib/condor/execute/slot4/dir_10843/userdir/anaconda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/bin/X11:/usr/games
+ PATH=/var/lib/condor/execute/slot4/dir_10843/userdir/anaconda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/bin/X11:/usr/games
+ [[ Linux == \L\i\n\u\x ]]
+ MINICONDA=Miniconda-3.7.0-Linux-x86_64.sh
+ mv condarc /home/slots/slot4/.condarc
mv: cannot stat `condarc': No such file or directory
```

At this point, I am unable and unwilling to work further. I think the CI needs some serious attention for documentation updates and general clean up. Yes, it appears to be working fine for now in most cases, but when it eventually breaks in the future -- and the likelihood of that is quite high -- unless the person tasked with fixing it was an original dev (even excluding myself), I suspect they will fail.

**Comment by scopatz** [comment]
>  I think the CI needs some serious attention for documentation updates and general clean up.

I have been saying this for a long time...

**Comment by scopatz** [comment]
This is what happens when there is neither someone dedicated and engaged in this activity nor actual communal responsibility and maintenance. One of these two things needs to happen for the project to be healthy.  

I strongly suspect that the same thing will happen with our release schedule.

**Comment by gidden** [comment]
These are largely gone now
